FROM node:16-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Expose port
EXPOSE 5000

# Development environment
ENV NODE_ENV=development

# Run with nodemon for hot reloading
CMD ["npm", "run", "dev"]